# Generated by Django 5.1.6 on 2025-09-14 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('noi_dung', models.TextField()),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
                ('danh_muc', models.CharField(blank=True, max_length=100)),
                ('noi_bat', models.BooleanField(default=False)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='bai_viet_images/')),
                ('tac_gia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_viets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_approve_post', 'Có thể phê duyệt bài viết')],
            },
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luans', to='bai_viet.baiviet')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phan_hoi', to='bai_viet.binhluan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NhomChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('thanh_vien', models.ManyToManyField(related_name='nhom_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TinNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('da_doc', models.BooleanField(default=False)),
                ('nguoi_gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_gui', to=settings.AUTH_USER_MODEL)),
                ('nguoi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['thoi_gian'],
            },
        ),
        migrations.CreateModel(
            name='TinNhanNhom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('nguoi_gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhans', to='bai_viet.nhomchat')),
            ],
            options={
                'ordering': ['thoi_gian'],
            },
        ),
        migrations.CreateModel(
            name='KetBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai', models.CharField(choices=[('cho', 'Đang chờ'), ('chap_nhan', 'Chấp nhận'), ('tu_choi', 'Từ chối')], default='cho', max_length=20)),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
                ('nguoi_gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loi_moi_gui', to=settings.AUTH_USER_MODEL)),
                ('nguoi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loi_moi_nhan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nguoi_gui', 'nguoi_nhan')},
            },
        ),
        migrations.CreateModel(
            name='ToCao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ly_do', models.TextField()),
                ('ngay_to_cao', models.DateTimeField(auto_now_add=True)),
                ('da_xu_ly', models.BooleanField(default=False)),
                ('bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_cao', to='bai_viet.baiviet')),
                ('nguoi_to_cao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('bai_viet', 'nguoi_to_cao')},
            },
        ),
    ]
