# Generated by Django 5.1.6 on 2025-09-28 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai_viet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nhom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhom', models.CharField(max_length=255)),
                ('mo_ta', models.TextField(blank=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('thanh_vien', models.ManyToManyField(blank=True, related_name='nhom_tham_gia', to=settings.AUTH_USER_MODEL)),
                ('truong_nhom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhom_quan_ly', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='baiviet',
            name='nhom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bai_viets', to='bai_viet.nhom'),
        ),
    ]
