# Generated by Django 5.1.6 on 2025-09-28 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai_viet', '0002_nhom_baiviet_nhom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nhomchat',
            name='truong_nhom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhomchat_quan_ly', to=settings.AUTH_USER_MODEL),
        ),
    ]
