# Generated by Django 5.1.6 on 2025-09-28 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai_viet', '0003_nhomchat_truong_nhom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='nhom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bai_viets', to='bai_viet.nhomchat'),
        ),
        migrations.RenameField(
            model_name='nhomchat',
            old_name='ten',
            new_name='ten_nhom',
        ),
        migrations.AlterField(
            model_name='nhomchat',
            name='truong_nhom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nhom_truong', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Nhom',
        ),
    ]
