# Generated by Django 5.1.6 on 2025-09-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai_viet', '0004_alter_baiviet_nhom_rename_ten_nhomchat_ten_nhom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhomchat',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='nhom_avatars/'),
        ),
    ]
