# Generated by Django 5.1.6 on 2025-10-05 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai_viet', '0005_nhomchat_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinnhannhom',
            name='nhom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhoms', to='bai_viet.nhomchat'),
        ),
    ]
