# Generated by Django 5.1.6 on 2025-10-05 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai_viet', '0007_tinnhan_attachment_tinnhan_is_read_tinnhan_reactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinnhannhom',
            name='nhom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhans', to='bai_viet.nhomchat'),
        ),
    ]
