# Generated by Django 5.1.6 on 2025-10-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai_viet', '0008_alter_tinnhannhom_nhom'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinnhan',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat/files/'),
        ),
        migrations.AddField(
            model_name='tinnhan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/images/'),
        ),
        migrations.AddField(
            model_name='tinnhannhom',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat/files/'),
        ),
        migrations.AddField(
            model_name='tinnhannhom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/images/'),
        ),
    ]
