# Generated by Django 5.1.6 on 2025-10-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai_viet', '0009_tinnhan_file_tinnhan_image_tinnhannhom_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinnhan',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bai_viet_image/'),
        ),
        migrations.AlterField(
            model_name='tinnhan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bai_viet_image/'),
        ),
    ]
