# Generated by Django 5.1.6 on 2025-10-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai_viet', '0010_alter_tinnhan_file_alter_tinnhan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinnhan',
            name='noi_dung',
            field=models.TextField(null=True),
        ),
    ]
