# Generated by Django 5.1.6 on 2025-10-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai_viet', '0011_alter_tinnhan_noi_dung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinnhan',
            name='noi_dung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tinnhannhom',
            name='noi_dung',
            field=models.TextField(blank=True, null=True),
        ),
    ]
