# Generated by Django 5.1.6 on 2025-10-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai_viet', '0012_alter_tinnhan_noi_dung_alter_tinnhannhom_noi_dung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinnhan',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bai_viet_file/'),
        ),
        migrations.AlterField(
            model_name='tinnhannhom',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bai_viet_file/'),
        ),
        migrations.AlterField(
            model_name='tinnhannhom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bai_viet_image/'),
        ),
    ]
