# Generated by Django 5.1.6 on 2025-10-19 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai_viet', '0013_alter_tinnhan_file_alter_tinnhannhom_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NhomThanhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('ngay_tham_gia', models.DateTimeField(auto_now_add=True)),
                ('nhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_thanh_vien', to='bai_viet.nhomchat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nhom', 'user')},
            },
        ),
    ]
