# Generated by Django 5.1.6 on 2025-11-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai_viet', '0015_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ketban',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ketban',
            name='trang_thai',
            field=models.CharField(choices=[('cho', 'Đang chờ'), ('chap_nhan', 'Đã chấp nhận'), ('tu_choi', 'Từ chối')], default='cho', max_length=20),
        ),
        migrations.RemoveField(
            model_name='ketban',
            name='ngay_gui',
        ),
    ]
