# Generated by Django 5.1.6 on 2025-11-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai_viet', '0016_alter_ketban_unique_together_alter_ketban_trang_thai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviet',
            name='luot_xem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
